#!/bin/bash

systemctl --user enable --now waybar.service
systemctl --user enable --now hyprpolkitagent.service
systemctl --user enable --now hyprpaper.service
systemctl enable --now docker.service
sudo usermod -aG docker $USER

